databases:
  - name: postgres
    databaseName: budget_app
    user: postgres_user
    plan: free

services:
  - type: web
    name: budget-wisely
    runtime: ruby
    plan: free
    buildCommand: "chmod +x bin/rails && ./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default